
x-defaults:

  default: &default
    restart: unless-stopped
    environment:
      PHP_ENABLE_XDEBUG: 0
#    ports:
#      - "80:80"
    volumes:
      - "/home/peter/github:/app"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

services:
  php74:
    <<: *default
    build:
      context: .
      dockerfile: apache/7.4/Dockerfile
    image: 'sarkedev/php:7.4-apache'
    container_name: php74

  php81:
    <<: *default
    build:
      context: .
      dockerfile: apache/8.1/Dockerfile
    image: 'sarkedev/php:8.1-apache'
    container_name: php81

  github-php74:
    <<: *default
    build:
      context: .
      dockerfile: apache/7.4/Dockerfile
    image: 'ghcr.io/sarkedev/php:7.4-apache'
    container_name: php74

  github-php81:
    <<: *default
    build:
      context: .
      dockerfile: apache/8.1/Dockerfile
    image: 'ghcr.io/sarke/php:8.1-apache'
    container_name: php81

  github-php84:
    <<: *default
    build:
      context: .
      dockerfile: apache/8.4/Dockerfile
    image: 'ghcr.io/sarke/php:8.4-apache'
    container_name: php84

  github-php84-fpm:
    <<: *default
    build:
      context: .
      dockerfile: fpm/8.4/Dockerfile
    image: 'ghcr.io/sarke/php:8.4-fpm'
    container_name: php84-fpm
