name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: 7.4
            dockerfile: apache/7.4/Dockerfile
            tag: sarkedev/php:7.4-apache
          - version: 8.1
            dockerfile: apache/8.1/Dockerfile
            tag: sarkedev/php:8.1-apache
          - version: 8.4
            dockerfile: apache/8.4/Dockerfile
            tag: sarkedev/php:8.4-apache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image for PHP ${{ matrix.version }}
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.dockerhub_tag }}
            ghcr.io/${{ matrix.dockerhub_tag }}
