name: ci

on:
  push:
    branches:
      - 'master'

jobs:

  docker_74:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 7.4
        id: docker_build_74
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile-7.4-apache
          tags: sarkedev/php:7.4-apache

  docker_81:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 8.1
        id: docker_build_81
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile-8.1-apache
          tags: sarkedev/php:8.1-apache

  docker_84:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 8.4 Apache
        id: docker_build_84
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile-8.4-apache
          tags: sarkedev/php:8.4-apache

  # docker_84_fpm:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push 8.4 FPM
  #       id: docker_build_84_fpm
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         file: Dockerfile-8.4-fpm
  #         tags: sarkedev/php:8.4-fpm
